name: invoice_pipeline
version: '1.0.0'
config-version: 2

profile: invoice_pipeline  

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  invoice_pipeline:
    silver:
      +materialized: incremental
      +incremental_strategy: merge  #upsert
      +schema: silver
    gold:
      +materialized: table          #for faster reads than a view, needed for analytics
      +schema: gold
    test_ignore:
      +materialized: ephemeral
      +schema: test_ignore