invoice_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: invoiceanalysispipeline  
      dataset: invoices              
      location: EU
      keyfile: "{{ env_var('GCP_KEYFILE_PATH', '/workspace/.gcp-service-account.json') }}"
      threads: 4
      timeout_seconds: 900