version: 2

models:
  - name: dim_vendor
    columns:
      - name: data_source_id
        tests:
          - not_null
      - name: vendor_no_id
        tests:
          - unique
          - not_null
      - name: vendor_no
        tests:
          - not_null
  - name: dim_buyer
    columns:
      - name: data_source_id
        tests:
          - not_null
      - name: buyer_no_id
        tests:
          - unique
          - not_null
      - name: buyer_no
        tests:
          - not_null