# This workflow is designed to keep GitHub Actions active so that actions keeps working even after 60 days of repo inactivity
name: Keep Alive

on:
  schedule:
    - cron: "0 0 1 * *"     # Runs on the first day of every month at midnight
jobs:
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2